[platformio]
default_envs = megaatmega2560
src_dir = src

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags =
  -std=gnu++11
  -Wall
  -Wextra
  -Wno-unused-parameter
  -DSERIAL_RX_BUFFER_SIZE=512
  -DSERIAL_TX_BUFFER_SIZE=96
monitor_speed = 250000
